spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}   # e.g. postgres
    password: ${DATABASE_PASSWORD}
logging:
  level:
    root: info
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publish-key: ${STRIPE_PUBLISHABLE_KEY}
  success-url: "https://learneyjourney.com/payment/success"
  cancel-url: "https://learneyjourney.com/payment/cancel"
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}