server:
  port:  ${PORT:8080}
spring:
  profiles:
    active: dev
app:
  allow-origins: "https://learneyjourney.com,https://www.learneyjourney.com,http://localhost:5173, https://learney-frontend-dev-24285490035.asia-southeast1.run.app"